import { createApp } from "vue";
import { createPinia } from "pinia";
import { createI18n } from "vue-i18n";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import App from "./App.vue";
import router from "./router";
import "./style.css";

const i18n = createI18n({
  legacy: false,
  locale: localStorage.getItem("locale") || "en",
  messages: {
    en: {
      brand: "NEXA",
      tagline: "Tools, news and rankings",
      about: "About",
      ads: "Advertise",
      contact: "Contact",
      login: "Log in",
      register: "Register",
      email: "Email",
      password: "Password",
      totp: "Authenticator code, leave blank if unused",
      createAccount: "Create account",
      haveAccount: "Already have an account? Log in",
      noAccount: "No account? Register",
      authFailed: "Could not sign in",
      "too many requests": "Too many attempts. Try again later.",
      "email exists": "This email is already registered.",
      "temporarily locked": "This account is temporarily locked.",
      "invalid credentials": "Email or password is incorrect.",
      "totp required": "Enter the authenticator code.",
      "invalid code": "That code is not valid.",
      "captcha required": "Slide the bar all the way to the right.",
      profile: "Profile",
      nickname: "Name",
      save: "Save",
      saved: "Saved",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm new password",
      passwordChanged: "Password updated",
      passwordMismatch: "The two new passwords do not match.",
      "password too short": "Use at least 8 characters.",
      slide: "Slide right to verify",
      slid: "Verified",
      category: "Category",
      linkName: "Name",
      linkUrl: "https://",
      linkDesc: "Short description",
      logoUrl: "Full icon URL",
      uploadIcon: "Upload",
      "image required": "Choose an image under 2 MB.",
      submitted: "Submitted for review",
      logout: "Log out",
      submit: "Submit a link",
      center: "Account",
      search: "Search this section",
      free: "FREE",
      hot: "HOT",
      adultTitle: "Adult links",
      adultBody: "This section is for adults. Confirm you are 18 or older.",
      enter: "Continue",
      back: "Go back",
      empty: "Nothing in this section yet.",
    },
    zh: {
      brand: "NEXA",
      tagline: "工具、资讯与排行",
      about: "关于我们",
      ads: "广告合作",
      contact: "联系方式",
      login: "登录",
      register: "注册",
      email: "邮箱",
      password: "密码",
      totp: "验证器验证码，未开启可留空",
      createAccount: "创建账号",
      haveAccount: "已有账号，去登录",
      noAccount: "没有账号，去注册",
      authFailed: "登录或注册失败",
      "too many requests": "尝试次数过多，请稍后再试。",
      "email exists": "这个邮箱已经注册过。",
      "temporarily locked": "账号暂时锁定。",
      "invalid credentials": "邮箱或密码不正确。",
      "totp required": "请填写验证器验证码。",
      "invalid code": "验证码不正确。",
      "captcha required": "请把滑块拖到最右侧。",
      profile: "个人资料",
      nickname: "昵称",
      save: "保存",
      saved: "已保存",
      currentPassword: "当前密码",
      newPassword: "新密码",
      confirmPassword: "确认新密码",
      passwordChanged: "密码已更新",
      passwordMismatch: "两次输入的新密码不一致。",
      "password too short": "新密码至少 8 位。",
      slide: "向右拖动完成验证",
      slid: "验证通过",
      category: "分类",
      linkName: "名称",
      linkUrl: "https://",
      linkDesc: "简短说明",
      logoUrl: "完整图标地址",
      uploadIcon: "本地上传",
      "image required": "请选择 2MB 以内的图片。",
      submitted: "已提交，等待审核",
      logout: "退出",
      submit: "提交链接",
      center: "个人中心",
      search: "搜索当前分类",
      free: "免费",
      hot: "热门",
      adultTitle: "成人链接",
      adultBody: "此分区仅面向成年人。请确认你已年满 18 岁。",
      enter: "继续",
      back: "返回",
      empty: "这个分类还没有内容。",
    },
  },
});

createApp(App).use(createPinia()).use(router).use(i18n).use(ElementPlus).mount("#app");
