import { createApp } from "vue";
import { createPinia } from "pinia";
import { createI18n } from "vue-i18n";
import App from "./App.vue";
import router from "./router";
import "./style.css";

const i18n = createI18n({
  legacy: false,
  locale: localStorage.getItem("locale") || "en",
  messages: {
    en: {
      brand: "NEXA",
      tagline: "Tools, news and rankings",
      about: "About",
      ads: "Advertise",
      contact: "Contact",
      login: "Log in",
      register: "Register",
      email: "Email",
      password: "Password",
      totp: "Authenticator code, leave blank if unused",
      createAccount: "Create account",
      haveAccount: "Already have an account? Log in",
      noAccount: "No account? Register",
      authFailed: "Could not sign in",
      "too many requests": "Too many attempts. Try again later.",
      "email exists": "This email is already registered.",
      "temporarily locked": "This account is temporarily locked.",
      "invalid credentials": "Email or password is incorrect.",
      "totp required": "Enter the authenticator code.",
      "invalid code": "That code is not valid.",
      "captcha required": "Slide the bar all the way to the right.",
      profile: "Profile",
      nickname: "Name",
      save: "Save",
      saved: "Saved",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm new password",
      passwordChanged: "Password updated",
      passwordMismatch: "The two new passwords do not match.",
      "password too short": "Use at least 8 characters.",
      "link exists": "This link is already listed.",
      slide: "Slide right to verify",
      slid: "Verified",
      category: "Category",
      linkName: "Name",
      nameRequired: "Name is required",
      linkUrl: "https://",
      linkDesc: "Short description",
      logoUrl: "Full icon URL",
      uploadIcon: "Upload",
      imageFormats: "Supported image formats: PNG, JPG, JPEG, GIF, WEBP, SVG",
      imageFormatsOnly: "Use PNG, JPG, JPEG, GIF, WEBP, or SVG",
      "image required": "Choose an image under 2 MB.",
      submitted: "Submitted. Review runs in the background.",
      logout: "Log out",
      submit: "Submit a link",
      center: "Account",
      proxyPool: "Free proxies",
      search: "Search this section",
      free: "FREE",
      hot: "HOT",
      adultTitle: "Adults only",
      adultLead: "This section ",
      adultWarn: "may include outbound links to adult films and videos",
      adultAfter: ". This site does not host or play those videos.",
      adultNote1: "The pages you open may include nudity, sexual content, or other material unsuitable for minors.",
      adultNote2: "Please follow the laws where you live. Do not continue if you are under 18, or if this kind of content is restricted for you.",
      adultNote3: "Choosing to continue is saved in this browser, so you will not be asked again on this device.",
      enter: "I am 18 or older. Continue",
      underAge: "I am under 18. Go back",
      back: "Go back",
      empty: "Nothing in this section yet.",
    },
    zh: {
      brand: "NEXA",
      tagline: "工具、资讯与排行",
      about: "关于我们",
      ads: "广告合作",
      contact: "联系方式",
      login: "登录",
      register: "注册",
      email: "邮箱",
      password: "密码",
      totp: "验证器验证码，未开启可留空",
      createAccount: "创建账号",
      haveAccount: "已有账号，去登录",
      noAccount: "没有账号，去注册",
      authFailed: "登录或注册失败",
      "too many requests": "尝试次数过多，请稍后再试。",
      "email exists": "这个邮箱已经注册过。",
      "temporarily locked": "账号暂时锁定。",
      "invalid credentials": "邮箱或密码不正确。",
      "totp required": "请填写验证器验证码。",
      "invalid code": "验证码不正确。",
      "captcha required": "请把滑块拖到最右侧。",
      profile: "个人资料",
      nickname: "昵称",
      save: "保存",
      saved: "已保存",
      currentPassword: "当前密码",
      newPassword: "新密码",
      confirmPassword: "确认新密码",
      passwordChanged: "密码已更新",
      passwordMismatch: "两次输入的新密码不一致。",
      "password too short": "新密码至少 8 位。",
      "link exists": "这个链接站内已经有了。",
      slide: "向右拖动完成验证",
      slid: "验证通过",
      category: "分类",
      linkName: "名称",
      nameRequired: "请填写名称",
      linkUrl: "https://",
      linkDesc: "简短说明",
      logoUrl: "完整图标地址",
      uploadIcon: "本地上传",
      imageFormats: "图片格式支持：PNG、JPG、JPEG、GIF、WEBP、SVG",
      imageFormatsOnly: "只支持 PNG、JPG、JPEG、GIF、WEBP、SVG",
      "image required": "请选择 2MB 以内的图片。",
      submitted: "已提交，正在自动审核",
      logout: "退出",
      submit: "提交链接",
      center: "个人中心",
      proxyPool: "免费代理池",
      search: "搜索当前分类",
      free: "免费",
      hot: "热门",
      adultTitle: "成年人内容提示",
      adultLead: "此栏目",
      adultWarn: "可能包含指向成年人影视的站外链接",
      adultAfter: "。本站不托管、也不播放这些影片。",
      adultNote1: "打开后的页面可能包含裸露、性相关内容，或其他不适合未成年人观看的材料。",
      adultNote2: "请遵守你所在地的法律规定。未满十八岁，或当地限制你访问这类内容时，请不要继续。",
      adultNote3: "选择继续后，会记在这台浏览器里，之后在这台设备上不用再次确认。",
      enter: "我已满十八岁，继续访问",
      underAge: "未满十八岁，返回首页",
      back: "返回",
      empty: "这个分类还没有内容。",
    },
  },
});

createApp(App).use(createPinia()).use(router).use(i18n).mount("#app");
