import { createApp } from "vue";
import { createPinia } from "pinia";
import { createI18n } from "vue-i18n";
import App from "./App.vue";
import router from "./router";
import { installTrack } from "./api";

installTrack(router);
import "./style.css";

const i18n = createI18n({
  legacy: false,
  locale: localStorage.getItem("locale") || "en",
  messages: {
    en: {
      brand: "NEXA",
      tagline: "Tools, news and rankings",
      about: "About",
      ads: "Advertise",
      contact: "Contact",
      login: "Log in",
      register: "Register",
      email: "Email",
      password: "Password",
      totp: "Authenticator code, leave blank if unused",
      createAccount: "Create account",
      haveAccount: "Already have an account? Log in",
      noAccount: "No account? Register",
      authFailed: "Could not sign in",
      "too many requests": "Too many attempts. Try again later.",
      "email exists": "This email is already registered.",
      "temporarily locked": "This account is temporarily locked.",
      "invalid credentials": "Email or password is incorrect.",
      "totp required": "Enter the authenticator code.",
      "invalid code": "That code is not valid.",
      "captcha required": "Slide the bar all the way to the right.",
      profile: "Profile",
      nickname: "Name",
      save: "Save",
      saved: "Saved",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm new password",
      passwordChanged: "Password updated",
      passwordMismatch: "The two new passwords do not match.",
      "password too short": "Use at least 8 characters.",
      "link exists": "This link is already listed.",
      slide: "Slide right to verify",
      slid: "Verified",
      category: "Category",
      linkName: "Name",
      nameRequired: "Name is required",
      linkUrl: "https://",
      linkDesc: "Short description",
      logoUrl: "Full icon URL",
      uploadIcon: "Upload",
      imageFormats: "Supported image formats: PNG, JPG, JPEG, GIF, WEBP, SVG",
      imageFormatsOnly: "Use PNG, JPG, JPEG, GIF, or WEBP",
      "image required": "Choose an image under 2 MB.",
      submitted: "Submitted. Review runs in the background.",
      logout: "Log out",
      noticeDetail: "Notice",
      submit: "Submit a link",
      center: "Account",
      proxyPool: "Free proxies",
      videoPlayer: "Video player",
      videoEntry: "Video parsing",
      videoLead: "Paste a public, directly playable video or page URL (MP4, WebM, M3U8), or pick a parser source to embed a page. The site embeds only the address you choose and does not endorse or control third-party content.",
      videoPlaceholder: "Paste a video or page URL",
      videoPlay: "Play",
      videoResolving: "Resolving…",
      videoFullscreen: "Fullscreen",
      videoClose: "Close",
      videoParserLabel: "Parser source (optional)",
      videoNoParser: "None (direct play)",
      videoParserPlaceholder: "Parser base URL, e.g. https://example.com/?url=",
      videoParserHint: "The list is loaded from Night Media → Video parsing. A source ending in url= appends the video address. A source containing {url} replaces that placeholder. Other links in the category are not parsers.",
      videoParserEmpty: "No parser sources loaded yet. You can type one below, or add links under the Night Media → Video parsing category.",
      videoParserCustom: "Custom (enter below)",
      videoUrlLabel: "Video / page URL",
      videoFrameNote: "Embedding the address you selected. Some sites block embedding; those will appear blank. The site does not control third-party content.",
      videoDragHint: "Drag the bottom-right corner to resize.",
      video_empty: "Please enter a video URL.",
      video_blocked: "This address is not allowed.",
      video_unreachable: "Could not open this address.",
      video_no_direct: "No publicly playable video found at this address.",
      video_too_many: "Too many requests. Try again later.",
      videoParserInvalid: "This is not a parser address. Use one that ends with url=, or clear it and play a public direct link.",
      videoPlayFailed: "This video cannot be played here.",
      videoStreamFailed: "This stream could not be played.",
      search: "Search this section",
      free: "FREE",
      hot: "HOT",
      adultTitle: "Adults only",
      adultLead: "This section ",
      adultWarn: "may include outbound links to adult films and videos",
      adultAfter: ". This site does not host or play those videos.",
      adultNote1: "The pages you open may include nudity, sexual content, or other material unsuitable for minors.",
      adultNote2: "Please follow the laws where you live. Do not continue if you are under 18, or if this kind of content is restricted for you.",
      adultNote3: "Choosing to continue is saved in this browser, so you will not be asked again on this device.",
      enter: "I am 18 or older. Continue",
      underAge: "I am under 18. Go back",
      back: "Go back",
      empty: "Nothing in this section yet.",
    },
    zh: {
      brand: "NEXA",
      tagline: "工具、资讯与排行",
      about: "关于我们",
      ads: "广告合作",
      contact: "联系方式",
      login: "登录",
      register: "注册",
      email: "邮箱",
      password: "密码",
      totp: "验证器验证码，未开启可留空",
      createAccount: "创建账号",
      haveAccount: "已有账号，去登录",
      noAccount: "没有账号，去注册",
      authFailed: "登录或注册失败",
      "too many requests": "尝试次数过多，请稍后再试。",
      "email exists": "这个邮箱已经注册过。",
      "temporarily locked": "账号暂时锁定。",
      "invalid credentials": "邮箱或密码不正确。",
      "totp required": "请填写验证器验证码。",
      "invalid code": "验证码不正确。",
      "captcha required": "请把滑块拖到最右侧。",
      profile: "个人资料",
      nickname: "昵称",
      save: "保存",
      saved: "已保存",
      currentPassword: "当前密码",
      newPassword: "新密码",
      confirmPassword: "确认新密码",
      passwordChanged: "密码已更新",
      passwordMismatch: "两次输入的新密码不一致。",
      "password too short": "新密码至少 8 位。",
      "link exists": "这个链接站内已经有了。",
      slide: "向右拖动完成验证",
      slid: "验证通过",
      category: "分类",
      linkName: "名称",
      nameRequired: "请填写名称",
      linkUrl: "https://",
      linkDesc: "简短说明",
      logoUrl: "完整图标地址",
      uploadIcon: "本地上传",
      imageFormats: "图片格式支持：PNG、JPG、JPEG、GIF、WEBP、SVG",
      imageFormatsOnly: "只支持 PNG、JPG、JPEG、GIF、WEBP",
      "image required": "请选择 2MB 以内的图片。",
      submitted: "已提交，正在自动审核",
      logout: "退出",
      noticeDetail: "公告详情",
      submit: "提交链接",
      center: "个人中心",
      proxyPool: "免费代理池",
      videoPlayer: "视频播放",
      videoEntry: "视频解析",
      videoLead: "粘贴一个公开可直接播放的视频地址或网页地址（支持 MP4、WebM、M3U8 直链），或选择一个解析源以嵌入页面。本站只嵌入你所选择的地址，不代表站点认可或控制第三方内容。",
      videoPlaceholder: "粘贴视频地址或网页地址",
      videoPlay: "播放",
      videoResolving: "解析中…",
      videoFullscreen: "全屏",
      videoClose: "关闭",
      videoParserLabel: "解析源（可选）",
      videoNoParser: "不使用（直链播放）",
      videoParserPlaceholder: "解析源地址，例如 https://example.com/?url=",
      videoParserHint: "下拉来自午夜媒体里的「视频解析」分类，每次打开都会重新读取。以 url= 结尾的地址会接上视频地址，包含 {url} 的地址会替换这个占位。分类里的项目主页不是解析接口。",
      videoParserEmpty: "暂未加载到解析源。你可以在下方手动填写，或在「午夜媒体 → 视频解析」分类里添加链接。",
      videoParserCustom: "自定义（在下方填写）",
      videoUrlLabel: "视频 / 网页地址",
      videoFrameNote: "正在嵌入你所选择的地址。部分站点禁止被嵌入，会显示空白。站点不控制第三方内容。",
      videoDragHint: "拖拽右下角可调整大小。",
      video_empty: "请填写视频地址。",
      video_blocked: "这个地址不允许访问。",
      video_unreachable: "打不开这个地址。",
      video_no_direct: "这个地址没有可直接播放的公开视频。",
      video_too_many: "请求过于频繁，请稍后再试。",
      videoParserInvalid: "这不是解析地址。请用以 url= 结尾的地址，或清空后播放公开直链。",
      videoPlayFailed: "这个视频无法在站内直接播放。",
      videoStreamFailed: "这个直播流无法播放。",
      search: "搜索当前分类",
      free: "免费",
      hot: "热门",
      adultTitle: "成年人内容提示",
      adultLead: "此栏目",
      adultWarn: "可能包含指向成年人影视的站外链接",
      adultAfter: "。本站不托管、也不播放这些影片。",
      adultNote1: "打开后的页面可能包含裸露、性相关内容，或其他不适合未成年人观看的材料。",
      adultNote2: "请遵守你所在地的法律规定。未满十八岁，或当地限制你访问这类内容时，请不要继续。",
      adultNote3: "选择继续后，会记在这台浏览器里，之后在这台设备上不用再次确认。",
      enter: "我已满十八岁，继续访问",
      underAge: "未满十八岁，返回首页",
      back: "返回",
      empty: "这个分类还没有内容。",
    },
  },
});

function setMeta(selector, attr, content) {
  const el = document.querySelector(selector);
  if (el && content) el.setAttribute(attr, content);
}

router.afterEach((to) => {
  const title = to.meta.title || "NEXA";
  if (!to.path || to.path === "/") return;
  document.title = title;
  setMeta('meta[name="description"]', "content", to.meta.description || "NEXA");
  setMeta('meta[property="og:title"]', "content", title);
  setMeta('meta[name="robots"]', "content", to.meta.index === false ? "noindex,nofollow" : "index,follow,max-image-preview:large");
  const canonical = document.querySelector('link[rel="canonical"]');
  if (canonical) canonical.setAttribute("href", to.path);
});

createApp(App).use(createPinia()).use(router).use(i18n).mount("#app");
